name: secureher_companion
description: "Companion app for SecureHer - Empowering Safety, Anytime, Anywhere."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_fonts: ^6.2.1
  intl: ^0.20.2
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.2
  permission_handler: ^12.0.1
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.4.2
  geolocator: ^14.0.2
  google_maps_flutter: ^2.9.0
  connectivity_plus: ^5.0.2
  firebase_core_platform_interface: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1  

flutter_icons:                     
  android: true
  ios: true
  image_path: "assets/icons/log.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
