name: secureher
description: "Secure Her â€“ Empowering Safety, Anytime, Anywhere."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_fonts: ^6.2.1
  intl: ^0.20.2
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.2
  permission_handler: ^12.0.1
  path_provider: ^2.1.3
  sensors_plus: ^6.0.3
  shake: ^3.0.0
  flutter_tts: ^4.2.3
  flutter_local_notifications: ^19.4.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.9.0
  camera: ^0.11.0+2
  audioplayers: ^6.0.0
  flutter_ringtone_player: ^4.0.0+2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  encrypt: ^5.0.3
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  workmanager: ^0.9.0
  flutter_background: ^1.2.0
  google_sign_in: ^7.2.0
  speech_to_text: ^7.2.0
  http: ^1.2.2
  video_player: ^2.8.6
  path: ^1.9.0
  connectivity_plus: ^5.0.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.12
  flutter_launcher_icons: ^0.13.1  

flutter_icons:                     
  android: true
  ios: true
  image_path: "assets/icons/log.png"

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/siren.mp3
    - assets/icons/log.png
